### ISSUE TITLE
It is unclear which version of elm is needed to use elm-d3

### ISSUE THREAD

**Issue by cognominal** [seliopou/elm-d3#16]
The compiling directive "elm --make ..." seems to belong to a past or future version of elm.
It seems impossible now to automate the installation of elm-d3.
Also it would be nice in the Readme to have links to working pages with the example files

See also :
https://groups.google.com/forum/#!topic/elm-discuss/LMtALynhA_M

**Comment by seliopou** [comment]
Hey there, thanks for the issue. The latest release&mdash;[v0.3.0](https://github.com/seliopou/elm-d3/releases/tag/v0.3.0)&mdash;is written against the elm-0.13 runtime API. My understanding is that elm-compiler has progressed to 0.14, which may have made some changes to the runtime API or standard libraries. This will be corrected in the near future (this weekend or next). However if you or anyone else out there reading would like to take a stab at fixing it, pull requests are always welcome.

Oh, and as I side note, I always mention in release notes when the library changes the elm runtime version that it targets in the release notes. For example, the last mention of an elm version in the release notes was [release v0.2.1](https://github.com/seliopou/elm-d3/releases/tag/v0.2.1). So if you're ever in doubt again, check there.

Links to examples are a good idea. [Here's one](http://computationallyendowed.com/examples/counters/) I'll collect some more and add them. Until then, I'll keep this open.

**Comment by flip111** [comment]
I just tried following the steps on the readme and everything works with the latest stable version of elm (0.15.1). Perhaps this issue is resolved now?

**Comment by seliopou** [comment]
Gonna leave this open until I get around to hosting some examples on gh-pages. Thanks for confirming that stuff works nicely in 0.15.1, though!

**Comment by marcmo** [comment]
same issue: your constraints do not permit the latest elm version (which is 0.16)
question: do you still maintain the d3.js binding?

**Comment by seliopou** [comment]
@marcmo the constraints are correct. I have yet to update the library to be compatible with 0.16. As the comment above states, when in doubt, check the release notes. I always include changes in compatibility with the release notes.

Closing this and opening another issue for hosting examples.
