### ISSUE TITLE
commitAndReleaseBuffer: invalid argument (invalid character)

### ISSUE THREAD

**Issue by NigelThorne** [seliopou/elm-d3#20]
Running on windows, with "Elm Platform 0.15.1"

```
PS D:\source> git clone https://github.com/seliopou/elm-d3.git
Cloning into 'elm-d3'...
remote: Counting objects: 655, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 655 (delta 0), reused 0 (delta 0), pack-reused 648
Receiving objects: 100% (655/655), 135.30 KiB | 113.00 KiB/s, done.
Resolving deltas: 100% (345/345), done.
Checking connectivity... done.
PS D:\source> cd .\elm-d3
PS D:\source\elm-d3> elm-make
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 2.1.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Packages configured successfully!
Success! Compiled 33 modules.
PS D:\source\elm-d3> elm-make examples/Circles.elm --output circles.html
Success! Compiled 2 modules.
elm-make.exe: circles.html: commitAndReleaseBuffer: invalid argument (invalid character)
```
The circles.html file is generated, but loading it in Chrome shows a blank screen.

**Comment by NigelThorne** [comment]
I removed the error by setting the command prompt code page with:
`chcp 65001`

**Comment by seliopou** [comment]
So I take it there is some unicode character somewhere in output. Do you have any additional information like line number, by any chance?

**Comment by NigelThorne** [comment]
nope. no clue. I included all the output. 
I think it's a haskell problem. 

http://techoverflow.net/blog/2014/06/23/how-to-solve-haskell-commitandreleasebuffer-invalid-argument-invalid-character-/

**Comment by seliopou** [comment]
If it's indeed a Haskell error, you should open an issue in the elm compiler repo about it.
