### ISSUE TITLE
Examples don't work with 0.15.1

### ISSUE THREAD

**Issue by NigelThorne** [seliopou/elm-d3#21]
I tried compiling the circles.elm demo. But all the demos do this.

```
d3 is not defined


Open the developer console for more details.
```

Voronoi.elm returns a different error. 

```
Detected errors in 1 module.
## ERRORS in examples/Voronoi.elm ##############################################

-- SYNTAX PROBLEM ----------------------------------------- examples/Voronoi.elm

I ran into something unexpected when parsing your code!

61| circles : D3 [D3.Voronoi.Point] D3.Voronoi.Point
                 ^
I am looking for one of the following things:

    "("
    "{"
    a type variable
    an upper case name
    whitespace

```
Is this an old elm syntax? Actually there were other errors first, but I changed lines 26 and 33 to 

```
26: import D3 exposing (..)
33: import Random exposing (..)
```

**Comment by seliopou** [comment]
The latest version of Elm does not allow you to control the linking of external JavaScript when generating html, so you must manually edit the generated html to include d3.js. This is documented in the README.

The voronoi error is the list type changed that happened. Went from `[a]` to `List a`.

**Comment by NigelThorne** [comment]
Though so. I'll raise a pull request if I fix this.

**Comment by seliopou** [comment]
Much appreciated. Only a few examples should be affected (I've already tested most of them), and most of the changes should be cosmetic. Circles is different because it uses the random number generator which is significantly different in 0.15.1.
