### ISSUE TITLE
Circles.elm - add delay to transition - produces safeValfn is not defined

### ISSUE THREAD

**Issue by mark2011** [seliopou/elm-d3#24]
I forked elm-d3 to mark2011/elm-d3 and added a delay to the transition in Circles.elm and when it is run in the browser, I get:

safeValfn is not defined
Open the developer console for more details.

Note I also added scripts:
- refresh-d3 - copies most recent version of d3.min.js to local folder
- insert-d3 [html file] - adds reference to local copy of d3.min.js

**Comment by mark2011** [comment]
FYI I did not update README for the scripts because I wasn't sure I could duplicate your voice.

**Comment by seliopou** [comment]
Thanks for the reporting the issue. For the other stuff, feel free to issue a pull request and I'll take a look.
