### ISSUE TITLE
Error: No versions of package 'seliopou/elm-d3' were found!

### ISSUE THREAD

**Issue by stereobooster** [seliopou/elm-d3#31]
```
elm-package install seliopou/elm-d3

Error: No versions of package 'seliopou/elm-d3' were found!
Is it spelled correctly?
```

Am I doing it wrong?

**Comment by seliopou** [comment]
As of now, elm-d3 is not distributed via the elm package manager. This may change in the future, but for now this is not a bug.

For now, to use elm-d3 in a project, you should vendor the code within your project and go from there.
